# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./ent
builds:
- 
  id: migrate
  main: ./cmd/migration/main.go
  binary: migrate
  goos:
  - linux
  - darwin
  - windows
  env:
  - CGO_ENABLED=0
- 
  id: create
  main: ./cmd/create/main.go
  binary: create
  goos:
  - linux
  - darwin
  - windows
  env:
  - CGO_ENABLED=0
- 
  id: query
  main: ./cmd/query/main.go
  binary: query
  goos:
  - linux
  - darwin
  - windows
  env:
  - CGO_ENABLED=0
- 
  id: query2
  main: ./cmd/query2/main.go
  binary: query2
  env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-ent"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
